<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-PK37ITT" failures="2" tests="4" name="test" time="41.065" errors="0" timestamp="2020-06-21T18:42:49 CDT">
  <testcase classname="testNG.NewTest" name="verify" time="10.908"/>
  <testcase classname="testNG.NewTest" name="verify1" time="9.675">
    <failure type="java.lang.AssertionError" message="expected [sai] but found [Log in | Website.com]">
      <![CDATA[java.lang.AssertionError: expected [sai] but found [Log in | Website.com]
at testNG.NewTest.verify1(NewTest.java:28)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- verify1 -->
  <testcase classname="testNG.NewTest1" name="verify" time="0.011"/>
  <testcase classname="testNG.NewTest1" name="verify1" time="0.012">
    <failure type="java.lang.AssertionError" message="expected [sai] but found [Log in | Website.com]">
      <![CDATA[java.lang.AssertionError: expected [sai] but found [Log in | Website.com]
at testNG.NewTest1.verify1(NewTest1.java:33)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- verify1 -->
</testsuite> <!-- test -->
